---
driver:
  name: vagrant
  username: vagrant
  password: vagrant

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept
  log_level: debug

platforms:
  - name: windows-2012r2
    driver:
      box: tas50/windows_2012r2
  - name: windows-2016
    driver:
      box: tas50/windows_2016
      customize:
        memory: 3072
  - name: windows-2019
    driver:
      box: tas50/windows_2019
      customize:
        memory: 3072

verifier:
  name: inspec

suites:
  - name: agent
    run_list:
      - recipe[sensu_test::agent]
      - recipe[sensu_test::ctl]
    verifier:
      inspec_tests:
        - test/integration/agent
    attributes:

  - name: ctl
    run_list:
      - recipe[sensu_test::ctl]
    verifier:
      inspec_tests:
        - test/integration/ctl
    attributes:
