---
name: windows

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  windows_agent:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Directory before
        run: dir D:\a\
      - name: Create Link
        run: New-Item -ItemType HardLink -Path D:\a\Cookbooks\ -Target D:\a\sensu-go-chef\sensu-go-chef
      - name: Directory after
        run: dir D:\a\
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: Chef Zero
        working-directory: D:\a\sensu-go-chef\sensu-go-chef
        run: chef-client -z -o recipe[sensu-go-chef::agent]
      - name: Run Chef Delivery
        uses: actionshub/chef-delivery@master
