---
name: windows

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  windows_agent:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: Create Link
        run: cmd /c mklink /d  D:\a\cookbooks\ D:\a\sensu-go-chef\
      - name: Install Other cookbooks
        working-directory: D:\a\
        run: berks install
      - name: Chef Zero
        working-directory: D:\a\
        env:
         CHEF_LICENSE: accept-no-persist
        run: chef-client -z -o sensu-go-chef::agent
      - name: Run Chef Delivery
        uses: actionshub/chef-delivery@master
      - name: Inspec
        run: chef exec inspec D:\a\sensu-go-chef\sensu-go-chef\test\integration\agent\agent_spec.rb
        env:
         CHEF_LICENSE: accept-no-persist
